# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-26 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='part1',
            name='code_gvk_au',
            field=models.CharField(default=1, max_length=6, verbose_name=b' \xd0\x9a\xd0\xbe\xd0\xb4 \xd0\xb2\xd0\xbe\xd0\xb4\xd0\xbe\xd0\xbf\xd0\xbe\xd0\xbb\xd1\x8c\xd0\xb7\xd0\xbe\xd0\xb2\xd0\xb0\xd1\x82\xd0\xb5\xd0\xbb\xd1\x8f \xd0\xbf\xd0\xbe \xd0\xb3\xd0\xbe\xd1\x81\xd1\x83\xd0\xb4\xd0\xb0\xd1\x80\xd1\x81\xd1\x82\xd0\xb2\xd0\xb5\xd0\xbd\xd0\xbd\xd0\xbe\xd0\xb3\xd0\xbe \xd0\xb2\xd0\xbe\xd0\xb4\xd0\xbd\xd0\xbe\xd0\xbc\xd1\x83 \xd0\xba\xd0\xb0\xd0\xb4\xd0\xb0\xd1\x81\xd1\x82\xd1\x80\xd1\x83 (\xd0\x93\xd0\x92\xd0\x9a)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part1',
            name='kod_wateruser_gvk',
            field=models.CharField(default=1, max_length=6, verbose_name=b' \xd0\x9a\xd0\xbe\xd0\xb4 \xd0\xb2\xd0\xbe\xd0\xb4\xd0\xbe\xd0\xbf\xd0\xbe\xd0\xbb\xd1\x8c\xd0\xb7\xd0\xbe\xd0\xb2\xd0\xb0\xd1\x82\xd0\xb5\xd0\xbb\xd1\x8f \xd0\xbf\xd0\xbe \xd0\xb3\xd0\xbe\xd1\x81\xd1\x83\xd0\xb4\xd0\xb0\xd1\x80\xd1\x81\xd1\x82\xd0\xb2\xd0\xb5\xd0\xbd\xd0\xbd\xd0\xbe\xd0\xb3\xd0\xbe \xd0\xb2\xd0\xbe\xd0\xb4\xd0\xbd\xd0\xbe\xd0\xbc\xd1\x83 \xd0\xba\xd0\xb0\xd0\xb4\xd0\xb0\xd1\x81\xd1\x82\xd1\x80\xd1\x83 (\xd0\x93\xd0\x92\xd0\x9a)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part1',
            name='lost_total',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part1',
            name='lost_transport',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part1',
            name='rash_oborot',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part1',
            name='trf_cod_au',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part1',
            name='trf_cod_wu1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part1',
            name='trf_cod_wu2',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part1',
            name='trf_cod_wu3',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part1',
            name='use_bez',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part1',
            name='use_tag1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part1',
            name='use_tag2',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part1',
            name='use_tag3',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part1',
            name='use_tag4',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part1',
            name='use_total',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part1',
            name='vol_au',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part1',
            name='vol_oborot',
            field=models.FloatField(default=1, verbose_name=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part1',
            name='vol_tag1',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part1',
            name='vol_tag2',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part1',
            name='vol_tag3',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part1',
            name='vol_tag4',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part1',
            name='vol_wu1',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part1',
            name='vol_wu2',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part1',
            name='vol_wu3',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
