# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-27 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inform', '0002_auto_20161226_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestItem',
            fields=[
                ('id_testitem', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name=20)),
                ('code', models.IntegerField()),
            ],
        ),
    ]
