# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inform', '0003_testitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part1',
            name='kod_category',
            field=models.IntegerField(max_length=2, verbose_name=b'\xd0\x9a\xd0\xbe\xd0\xb4 \xd0\xba\xd0\xb0\xd1\x82\xd0\xb5\xd0\xb3\xd0\xbe\xd1\x80\xd0\xb8\xd0\xb8 \xd0\xba\xd0\xb0\xd1\x87\xd0\xb5\xd1\x81\xd1\x82\xd0\xb2\xd0\xb0 \xd0\xb2\xd0\xbe\xd0\xb4\xd1\x8b'),
        ),
    ]
